### ISSUE TITLE
[FEATURE] Support for openshift configmap objects

### ISSUE THREAD

**Issue by ftapiat** [ftapiat/env-compare-rest#4]
Allow loading the configmap using "data" key:

This is not currently supported:
```yaml
data:
  first.key: 'foo'
  second.key: 'bar'
```
